# DreamSkull

# Messages
send_message: true
op_message: true

# PvP
drop-allow-totem: true
auto-kill: false
stats-active: true

# Looting
looting-influence: true
looting-pct-more: 10.8

# Spawner
spawner-loot: false

# Chance to drop: %
entities:
  player: 10
  creeper: 50
  ghast: 49.95
  zombie: 100
  villager: 20
  bat: 0.1