# DreamSkull

send_message: true
drop-allow-totem: true
auto-kill: false
looting-influence: true
looting-pct-more: 10

# Chance to drop: %
entities:
  player: 10
  creeper: 50
  ghast: 50
  zombie: 100
  villager: 20
  bat: 10